# Replace Weight(Dense & Convolution2d)
---

In [1]:
import tensorflow as tf

In [2]:
# 亂數 Init
weightInit = tf.random_normal_initializer(0, 0.3)
biasInit = tf.random_normal_initializer(0, 0.1)

In [3]:
input = tf.placeholder(
    tf.float32,
    [None, 2]
)

# 兩個測試網路
t1layer1 = tf.layers.dense(
    inputs=input,
    units=2,
    kernel_initializer=weightInit,
    bias_initializer=biasInit,
    activation=tf.nn.relu,
    name="Test1_Layer1"
)
print(t1layer1)
t2layer1 = tf.layers.dense(
    inputs=input,
    units=2,
    kernel_initializer=weightInit,
    bias_initializer=biasInit,
    activation=tf.nn.relu,
    name="Test2_Layer1"
)
print(t2layer1)

Tensor("Test1_Layer1/Relu:0", shape=(?, 2), dtype=float32)
Tensor("Test2_Layer1/Relu:0", shape=(?, 2), dtype=float32)


In [4]:
session = tf.Session()
session.run(tf.global_variables_initializer())

In [5]:
def PrintWeight(name):
    weightNode = tf.get_default_graph().get_tensor_by_name(name + "/kernel:0")
    biasNode = tf.get_default_graph().get_tensor_by_name(name + "/bias:0")
    print("Weight:")
    print(session.run(weightNode))
    print("Bias:")
    print(session.run(biasNode))

In [6]:
print("Layer1")
print(PrintWeight("Test1_Layer1"))
print()
print("Layer2")
print(PrintWeight("Test2_Layer1"))

Layer1
Weight:
[[-0.62110716 -0.35859823]
 [-0.176432   -0.09379353]]
Bias:
[-0.1118173  -0.08529119]
None

Layer2
Weight:
[[-0.12960988 -0.11410836]
 [-0.11023621 -0.35176253]]
Bias:
[ 0.23755129  0.04878923]
None


In [7]:
# 拿 Node
t1weightNode = session.graph.get_tensor_by_name("Test1_Layer1/kernel:0")
t1biasNode = session.graph.get_tensor_by_name("Test1_Layer1/bias:0")
t2weightNode = session.graph.get_tensor_by_name("Test2_Layer1/kernel:0")
t2biasNode = session.graph.get_tensor_by_name("Test2_Layer1/bias:0")

print(t1weightNode)
print(t1biasNode)
print(t2weightNode)
print(t2biasNode)

# 取代
assignWeightNode = tf.assign(t2weightNode, t1weightNode)
assignBiasNode = tf.assign(t2biasNode, t1biasNode)
session.run([assignWeightNode, assignBiasNode]);

Tensor("Test1_Layer1/kernel:0", shape=(2, 2), dtype=float32_ref)
Tensor("Test1_Layer1/bias:0", shape=(2,), dtype=float32_ref)
Tensor("Test2_Layer1/kernel:0", shape=(2, 2), dtype=float32_ref)
Tensor("Test2_Layer1/bias:0", shape=(2,), dtype=float32_ref)


In [8]:
print("Layer1")
print(PrintWeight("Test1_Layer1"))
print()
print("Layer2")
print(PrintWeight("Test2_Layer1"))

Layer1
Weight:
[[-0.62110716 -0.35859823]
 [-0.176432   -0.09379353]]
Bias:
[-0.1118173  -0.08529119]
None

Layer2
Weight:
[[-0.62110716 -0.35859823]
 [-0.176432   -0.09379353]]
Bias:
[-0.1118173  -0.08529119]
None
