# 測試儲存和回覆變數
---

In [1]:
import tensorflow as tf
import os

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


設定變數

In [2]:
# 設定變數
input = tf.placeholder(tf.float32, [None, 10])
layer1 = tf.layers.dense(
    inputs=input,
    units=1,
    kernel_initializer=tf.random_normal_initializer(mean=0, stddev= 0.3),
    bias_initializer=tf.random_normal_initializer(mean=0, stddev= 0.1),
    name = "Layer1"
)
print(layer1.name)

Layer1/BiasAdd:0


In [3]:
# 使用 Session
session = tf.Session()
session.run(tf.global_variables_initializer())

In [4]:
layer1Weight = tf.get_default_graph().get_tensor_by_name(name="Layer1/kernel:0")
session.run(layer1Weight)

array([[-0.04241094],
       [-0.40176252],
       [ 0.17237444],
       [ 0.48718777],
       [ 0.44358596],
       [ 0.07015489],
       [ 0.38135642],
       [ 0.00888421],
       [-0.16738757],
       [-0.01494874]], dtype=float32)

In [5]:
# 設定一個 存擋器
saver = tf.train.Saver()

In [6]:
if(not os.path.exists("./models/")):
    os.mkdir("./models/")
saver.save(session, "./models/test", global_step=100)

'./models/test-100'

# 將變數清空
---

In [11]:
#tf.reset_default_graph()
session = tf.Session()
session.run(tf.global_variables_initializer())

In [12]:
# 亂掉的 Weight
session.run(layer1Weight)

array([[ 0.02839328],
       [-0.1802434 ],
       [-0.42186376],
       [-0.12839763],
       [ 0.5559333 ],
       [-0.31475022],
       [-0.21113862],
       [ 0.00826168],
       [ 0.34905958],
       [-0.68742585]], dtype=float32)

In [13]:
saver.restore(session, "./models/test-100")

# 恢復正常的 Weight
session.run(layer1Weight)

INFO:tensorflow:Restoring parameters from ./models/test-100


INFO:tensorflow:Restoring parameters from ./models/test-100


array([[-0.04241094],
       [-0.40176252],
       [ 0.17237444],
       [ 0.48718777],
       [ 0.44358596],
       [ 0.07015489],
       [ 0.38135642],
       [ 0.00888421],
       [-0.16738757],
       [-0.01494874]], dtype=float32)

# 結論
---
1. 必須要建好 Graph 來能使用 restore 得 function，根據名字把 Graph 重建回來
2. 如果是要 load Graph 的話，是需要用其他的 Function
3. tf.train.Saver() 的路徑，一定要建過，路徑不存在會出現 error