# Python 須知

## Python 輸出
---

EX: "True: {0}".format(1)  
利用 format 的函數是將裡面的數字轉成字串  
填到參數{0}裡

In [1]:
print("True: {0}".format(1))
print("True: {0}".format([0,1,2,3]))
print("{0} Hello {1}".format(1,3))

True: 1
True: [0, 1, 2, 3]
1 Hello 3


## Python Array 格式
---
numpy 是 Python 數學計算的模組  
\[從哪一個開始(A):到哪一個結束(B)\]  
記得顯示的數目是 B-A  
shape => 看資料的維度

In [2]:
import numpy as np
test_array = np.array([[ 0,  1,  2,  3,  4],
                       [ 5,  6,  7,  8,  9],
                       [12, 13, 14, 15, 16],
                       [ 8,  2,  3,  1,  6]])
print("0:0 =>\n", test_array[0:0],"\n")
print("0:1 =>\n", test_array[0:1],"\n")
print("0:2 =>\n", test_array[0:2],"\n")
print("0:3 =>\n", test_array[0:3],"\n")
print("1:1 =>\n", test_array[1:1],"\n")
print("1:2 =>\n", test_array[1:2],"\n")
print("維度是", test_array.shape)
#data.test.labels[0:2, :]

0:0 =>
 [] 

0:1 =>
 [[0 1 2 3 4]] 

0:2 =>
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

0:3 =>
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [12 13 14 15 16]] 

1:1 =>
 [] 

1:2 =>
 [[5 6 7 8 9]] 

維度是 (4, 5)


## 陣列裡面放 For
---
陣列裡面可以放一個 for 來產生一維資料  
numpy array 裡面 argmax  
是拿出整個陣列裡  
最大的值的 Index (從0開始)

In [3]:
testMax = np.array([label.argmax() for label in test_array])
print(testMax)

[4 4 4 0]
